### ISSUE TITLE
教师没有注册入口，怎么登陆？

### ISSUE THREAD

**Issue by DiuDiugirl** [filow/examal#1]
hi~
想问一下，教师登陆的时候没有注册入口，在数据库里直接添加的话，密码是加密，要怎么加入密码？还是有别的方法呢？

**Comment by filow** [comment]
出于安全性考虑并没有增加教师注册的功能，请在服务器的程序根目录下运行
    rails console
而后输入
    Teacher.create({name:"admin", password:"123456",password_confirmation:"123456"})
就可以创建教师账户了
这个项目已经有段时间没维护了，输入的内容可能有点错误，如果出错了的话你可以看看app/models/teacher.rb
name和password里面的值你可以自己改，password至少6位。

创建完第一个用户之后其他的用户就都可以在后台添加了。

如果还有什么疑问欢迎回复~~~最近要出去旅游可能会回的比较慢，还请见谅！

**Comment by DiuDiugirl** [comment]
已经搞定了～谢谢～旅行愉快～～

**Comment by kurexi** [comment]
@filow 应该在seeds中添加你说的脚本

**Comment by filow** [comment]
好的，我也觉得该加上

**Comment by filow** [comment]
已经添加了管理员生成脚本了
