### ISSUE TITLE
不是管理员的教师无法创建考试

### ISSUE THREAD

**Issue by kurexi** [filow/examal#2]
创建考试时要启发before action: :edit_or_delete_right，然后再edit_or_delete_right方法中先判断是否为管理员再判断目前题目的老师id。但是题目 @quetion 没有初始化。Bug

https://github.com/filow/examal/blob/master/app/controllers/exams_controller.rb 118行

**Comment by filow** [comment]
嗯，等我今天有空的时候解决一下

**Comment by filow** [comment]
bug已经修复了，你看一下
